name: Deploy React App to EC2 with Docker

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Docker
        uses: docker/setup-buildx-action@v2

      - name: Build Docker Image
        run: |
          cd Frontend
          docker build -t react-app .

      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.EC2_SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.EC2_PUBLIC_IP }} >> ~/.ssh/known_hosts

      - name: Push Docker Image to EC2
        run: |
          docker save react-app | bzip2 | ssh ubuntu@${{ secrets.EC2_PUBLIC_IP }} 'bunzip2 | docker load'

      - name: Run Docker Container on EC2
        run: |
          ssh ubuntu@${{ secrets.EC2_PUBLIC_IP }} << 'EOF'
            # Stop and remove the previous container if it exists
            docker stop react-container || true
            docker rm react-container || true

            # Create a directory for SSL certificates if not present
            mkdir -p /etc/letsencrypt/live/quicktradehub.in

            # Mount SSL certificates from EC2 host if available
            # Assuming the certificates are already generated and placed in /etc/letsencrypt on the host machine
            docker run -d \
              -v /etc/letsencrypt/live/quicktradehub.in:/etc/letsencrypt/live/quicktradehub.in:ro \
              -p 80:80 -p 443:443 \
              --name react-container \
              -e SSL_CERTIFICATE_PATH=/etc/letsencrypt/live/quicktradehub.in/fullchain.pem \
              -e SSL_KEY_PATH=/etc/letsencrypt/live/quicktradehub.in/privkey.pem \
              react-app
          EOF
