name: Deploy React App to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Dependencies & Build React App
        run: |
          cd Frontend
          npm install
          npm run build

      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.EC2_SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H 13.60.97.119 >> ~/.ssh/known_hosts

      - name: Deploy to EC2
        run: |
          rsync -avz -e "ssh -o StrictHostKeyChecking=no" Frontend/build/ ubuntu@13.60.97.119:/home/ubuntu/react-app

      - name: Restart React App on EC2
        run: |
          ssh ubuntu@13.60.97.119 << 'EOF'
            cd /home/ubuntu/react-app
            pm2 delete react-app || true
            pm2 serve /home/ubuntu/react-app/build 3000 --name react-app --spa
          EOF
