name: Deploy React App to EC2 using Docker (No Docker Hub)

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Build React App
        run: |
          cd Frontend
          npm install
          npm run build

      - name: Build Docker Image
        run: |
          cd Frontend
          docker build -t react-app:latest .

      - name: Save Docker Image as Tar File
        run: |
          docker save -o react-app.tar react-app:latest

      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.EC2_SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H 13.60.97.119 >> ~/.ssh/known_hosts

      - name: Copy Docker Image to EC2
        run: |
          scp -o StrictHostKeyChecking=no react-app.tar ubuntu@13.60.97.119:/home/ubuntu/

      - name: Deploy to EC2
        run: |
          ssh ubuntu@13.60.97.119 << 'EOF'
            # Load Docker Image
            docker load -i /home/ubuntu/react-app.tar

            # Stop and remove existing container
            docker stop react-container || true
            docker rm react-container || true

            # Run new container
            docker run -d -p 80:3000 --name react-container react-app:latest
          EOF
