name: Deploy React App to EC2 instance

on:
  push:
    branches:
      - main  # Change if needed

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup SSH Key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.EC2_SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H 13.60.97.119 >> ~/.ssh/known_hosts

      - name: Deploy to EC2
        run: |
          ssh -o StrictHostKeyChecking=no ubuntu@13.60.97.119 << 'EOF'
            # Ensure frontend folder exists
            if [ ! -d "~/frontend" ]; then
              git clone git@github.com:QuickTradeHub/QuickTradeHub.git frontend
            fi

            cd frontend
            git fetch --all
            git reset --hard origin/main
            git pull origin main

            npm install
            npm run build

            # Stop and remove any existing container
            docker stop react-container || true
            docker rm react-container || true

            # Remove old image to free space
            docker rmi react-app || true

            # Build and run the new container
            docker build -t react-app .
            docker run -d -p 80:80 --name react-container react-app
          EOF
