name: Deploy React App to EC2 using Docker

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Build React App
        run: |
          cd Frontend
          npm install
          npm run build

      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKER_HUB_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_HUB_USERNAME }}" --password-stdin

      - name: Build & Push Docker Image
        run: |
          cd Frontend
          docker build -t ${{ secrets.DOCKER_HUB_USERNAME }}/react-app:latest .
          docker push ${{ secrets.DOCKER_HUB_USERNAME }}/react-app:latest

      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.EC2_SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H 13.60.97.119 >> ~/.ssh/known_hosts

      - name: Deploy to EC2
        run: |
          ssh ubuntu@13.60.97.119 << 'EOF'
            # Pull latest Docker image
            docker pull ${{ secrets.DOCKER_HUB_USERNAME }}/react-app:latest

            # Stop and remove existing container
            docker stop react-container || true
            docker rm react-container || true

            # Run new container
            docker run -d -p 80:3000 --name react-container ${{ secrets.DOCKER_HUB_USERNAME }}/react-app:latest
          EOF
