name: Deploy Notification Service to EC2 with Docker

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Docker
        uses: docker/setup-buildx-action@v2

      - name: Build Docker Image
        run: |
          cd NotificationService
          docker build -t notification-service .

      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.EC2_SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.EC2_PUBLIC_IP }} >> ~/.ssh/known_hosts

      - name: Push Docker Image to EC2
        run: |
          docker save notification-service | bzip2 | ssh ubuntu@${{ secrets.EC2_PUBLIC_IP }} 'bunzip2 | docker load'

      - name: Run Docker Container on EC2
        run: |
          ssh ubuntu@${{ secrets.EC2_PUBLIC_IP }} << 'EOF'
            docker stop notification-service || true
            docker rm notification-service || true
            docker run -d -p 3000:3000 --name notification-service notification-service
          EOF
