name: Deploy OrderService to EC2 with Docker

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'

      - name: Restore Dependencies
        run: |
          cd OrderService/OrderServiceProject/OrderServiceProject
          dotnet restore

      - name: Build Application
        run: |
          cd OrderService/OrderServiceProject/OrderServiceProject
          dotnet build --configuration Release --no-restore

      - name: Publish Application
        run: |
          cd OrderService/OrderServiceProject/OrderServiceProject
          dotnet publish --configuration Release --output ./publish

      - name: Setup Docker
        uses: docker/setup-buildx-action@v2

      - name: Build Docker Image
        run: |
          cd OrderService/OrderServiceProject/OrderServiceProject
          docker build -t orderservice .

      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.EC21_SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.EC21_PUBLIC_IP }} >> ~/.ssh/known_hosts

      - name: Push Docker Image to EC2
        run: |
          docker save orderservice | bzip2 | ssh ubuntu@${{ secrets.EC21_PUBLIC_IP }} 'bunzip2 | docker load'

      - name: Run EF Core Migrations on EC2
        run: |
          ssh ubuntu@${{ secrets.EC21_PUBLIC_IP }} << 'EOF'
            docker run --rm --env ConnectionStrings__DefaultConnection="Server=localhost;Database=OrderServiceDb;User Id=sa;Password=YourPassword123;" orderservice dotnet ef database update
          EOF

      - name: Run Docker Container on EC2
        run: |
          ssh ubuntu@${{ secrets.EC21_PUBLIC_IP }} << 'EOF'
            docker stop orderservice || true
            docker rm orderservice || true
            docker run -d -p 5142:5142 --name orderservice \
              -e ConnectionStrings__DefaultConnection="Server=localhost;Database=OrderServiceDb;User Id=sa;Password=YourPassword123;" \
              orderservice
          EOF
